<div class="search">
    <br>

    <div id="tabs">
        <ul>
            <li><a href="#tab-1">Errors</a></li>
        </ul>

        <div id="tabs-1" style="overflow:auto;">
            <h1>An Error Has Occurred</h1>
            <h2><?php echo $this->message ?></h2>

            <?php if (isset($this->exception)) { ?>

                <h3>Exception information:</h3>
                <p>
                    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                </p>

                <h3>Stack trace:</h3>
                <p><?php echo $this->exception->getTraceAsString() ?></p>

                <h3>Request Parameters:</h3>
                <p><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></p>

                <?php
            }
            ?>                        

            <h3>This information has automatically been sent to FormaServe<h3>

                    <div id="paging" style="text-align:right; margin: 10px;">
                        <input style ="color:green" type="submit" class="button" value="Close Tab" onclick="close_tab();" >
                    </div>

                    </div>
                    </div>
