<?php
$this->title = "Delete Configuration Item";
$this->headTitle($this->title);
?>

<div class="search">
    <p>&nbsp;</p>
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Confirm Delete</a></li>
        </ul>
        <div id="tabs-1">
            <form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
                <table style="margin: auto;">
                    <tr>
                        <td>Key</td>
                        <td><?= $this->configuration['parameters'] ?></td>
                    </tr>
                    <tr>
                        <td style="width: 150px;">Value</td>
                        <td style="width: 150px;"><?= $this->configuration['parm_value'] ?></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <br><br>
                            <input type="hidden" name="parameters" value="<?= $this->configuration['parameters']; ?>">
                            <input type="hidden" name="parm_value" value="<?= $this->configuration['parm_value']; ?>">
                            <input type="submit" name="del" value="Yes" style="width:50px;">
                            <input type="submit" name="del" value="No" style="width:50px;">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>