<?php
$this->title = "CSM - Update Configuration Item";
$this->headTitle($this->title);
?>

<div class="search">
    <p>&nbsp;</p>
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Update Configuration</a></li>
        </ul>
        <div id="tabs-1">
            <form id="search" action="/configuration/update/" method="post">
                <table style="margin: auto;">
                    <tr>
                        <td>Key</td>
                        <td><?= $this->key ?><input type="hidden" name="key" value="<?= $this->key ?>"><input type="hidden" name="id" value="<?= $this->id ?>"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px;">Value</td>
                        <td style="width: 150px;"><input type="text" name="value" value="<?= $this->value ?>"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px;">Text</td>
                        <td style="width: 150px;"><input type="text" name="text" value="<?= $this->text ?>"></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Save"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

