<div class="search">
    <p>&nbsp;</p>
    <div id="tabs">

        <input type="hidden" name="records" id="records" value="<?= $this->records ?>">

        <ul>
            <li>
                <a href="#tabs-1">Views</a>
            </li>
            <li>
                <a href="#tabs-2">Search</a>
            </li>
        </ul>

        <!--Tickets Selection-->
        <div id="tabs-1" style="overflow:auto;">
            <form>
                <table style="margin: auto;" cellspacing="0" border-spacing="0">
                    <tr>
                        <td>
                            <div id="paging">
                                <input type="submit" value="All Open" id="ViewA" class="button" style="<?= trim($this->clrA) ?>"/><input type="submit" value="All" id="ViewB" class="button" style="<?= trim($this->clrB) ?>"/><input type="submit" value="Follow Up" id="ViewC" class="button" style="<?= trim($this->clrC) ?>"/>
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>

        <!--Search Selection-->
        <div id="tabs-2" style="overflow:auto;">
            <form id="search2" action="/enquiries/index/f/2" method="post">
                <table style="margin: auto;">
                    <tr>
                        <td style="width: 30px">&nbsp;</td>
                        <td style="width: 200px">
                            <select id="field1" name="field1">
                                <option value=""></option>
                                <option value="ENQ_NO">Enquiry No</option>
                                <option value="UPPER(ENQUIRER)">Enquirer</option>
                                <option value="UPPER(COMPANY)">Company</option>
                                <option value="UPPER(LOCATION)">Location</option>
                                <option value="STATUS">Status</option>
                                <option value="FOLLOW_UP">Follow Up Date</option>
                                <option value="STUDENT">Student</option>
                                <option value="COURSE">Course Code</option>
                                <option value="START_DATE">Course Date</option>
                                <option value="WILDCARD">Wildcard</option>
                            </select>
                        </td>
                        <td style="width: 50px">
                            <select id="op1" name="op1" style="width: 75px;">
                                <option value="=">&#61;</option>
                                <option value=&gt;>&gt;</option>
                                <option value=&lt;>&lt;</option>
                                <option value=&lt;&gt;>&lt;&gt;</option>
                                <option value=&gt;&#61;>&gt;&#61;</option>
                                <option value=&lt;&#61;>&lt;&#61;</option>
                                <option value='like'>Like</option>
                                <option value='nlike'>Not Like</option>
                            </select>
                        </td>
                        <td style="width: 200px; text-align:left;">
                            <input id="text1" name="text1" type="text" value="<?= $this->text1 ?>" style="width: 200px"/>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <select id="ao2" name="ao2" style="width: 60px;">
                                <option value=""></option>
                                <option value="and">And</option>
                                <option value="or">Or</option>
                            </select></td>
                        <td>
                            <select id="field2" name="field2" style="width: 200px">
                                <option value=""></option>
                                <option value="ENQ_NO">Enquiry No</option>
                                <option value="UPPER(ENQUIRER)">Enquirer</option>
                                <option value="UPPER(COMPANY)">Company</option>
                                <option value="UPPER(LOCATION)">Location</option>
                                <option value="STATUS">Status</option>
                                <option value="FOLLOW_UP">Follow Up Date</option>
                                <option value="STUDENT">Student</option>
                                <option value="COURSE">Course Code</option>
                                <option value="START_DATE">Course Date</option>
                            </select>
                        </td>
                        <td>
                            <select id="op2" name="op2" style="width: 75px;">
                                <option value=""></option>
                                <option value="=">=</option>
                                <option value=&gt;>&gt;</option>
                                <option value=&lt;>&lt;</option>
                                <option value=&lt;&gt;>&lt;&gt;</option>
                                <option value=&gt;&#61;>&gt;&#61;</option>
                                <option value=&lt;&#61;>&lt;&#61;</option>
                                <option value='like'>Like</option>
                                <option value='nlike'>Not Like</option>
                            </select>
                        </td>
                        <td style="text-align:left;">
                            <input id="text2" name="text2" type="text" value="<?= $this->text2 ?>" style="width: 200px"/>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <select id="ao3" name="ao3" style="width: 60px;">
                                <option value=""></option>
                                <option value="and">And</option>
                                <option value="or">Or</option>
                            </select></td>
                        <td>
                            <select id="field3" name="field3">
                                <option value=""></option>
                                <option value="ENQ_NO">Enquiry No</option>
                                <option value="UPPER(ENQUIRER)">Enquirer</option>
                                <option value="UPPER(COMPANY)">Company</option>
                                <option value="UPPER(LOCATION)">Location</option>
                                <option value="STATUS">Status</option>
                                <option value="FOLLOW_UP">Follow Up Date</option>
                                <option value="STUDENT">Student</option>
                                <option value="COURSE">Course Code</option>
                                <option value="START_DATE">Course Date</option>
                            </select>
                        </td>
                        <td>
                            <select id="op3" name="op3" style="width: 75px;">
                                <option value=""></option>
                                <option value="=">=</option>
                                <option value=&gt;>&gt;</option>
                                <option value=&lt;>&lt;</option>
                                <option value=&lt;&gt;>&lt;&gt;</option>
                                <option value=&gt;&#61;>&gt;&#61;</option>
                                <option value=&lt;&#61;>&lt;&#61;</option>
                                <option value='like'>Like</option>
                                <option value='nlike'>Not Like</option>
                            </select>
                        </td>
                        <td style="text-align:left;">
                            <input id="text3" name="text3" type="text" value="<?= $this->text3 ?>" style="width: 200px"/>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align:center;">
                            <div id="paging">
                                <input type="submit" value="Search" class="button" /><input type="submit" value="Clear" class="button" onclick="reset_form();
                                        return false;" />
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    
    <p style="text-align: right; font-size: 1em;"><input id="new" type="submit" value="New Enquiry" class="button" onclick="var win=window.open('/enquiries/update/f/A', '_blank');"/></p>

    <div id="tabs2">
        <ul>
            <li>
                <a href="#tabs-1">&nbsp;</a>
            </li>
        </ul>
        <div id="tabs-1" style="overflow:auto;">

            <?= $this->paginationControl($this->header, 'Sliding', '/enquiries_pagination.phtml', array('paging_qs' => $this->paging_qs, 'f' => $this->f, 'sel' => $this->sel)); ?> 
            <input type="hidden" name="sort" id="sort"> 
            <br>
            <table class="resultset">
                <tr>
                    <th style="width: 18px">&nbsp;</th>
                    <th style="width: 3px">&nbsp;</th>
                    <th style="width: 18px">&nbsp;</th>
                    <th style="width: 3px">&nbsp;</th>
                    <th style="text-align:left;">No</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th style="text-align:left;">Enquirer</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th>Company</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th style="text-align:center">Email</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th>Telephone</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th>Location</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th>Price</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th>Status</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th style="text-align:center;">Chased</th>
                    <th style="width: 10px">&nbsp;</th>
                    <th style="text-align:center">Follow Up</th>
                    <th style="width: 3px">&nbsp;</th>
                    <th style="width: 18px">&nbsp;</th>
                </tr>
                <?php foreach ($this->header as $head) : ?>
                    <tr     
                    <?php
                    if ($head->STATUS == 0) {
                        echo "style=\"color:RED;\"";
                    }
                    if ($head->STATUS == 10) {
                        echo "style=\"color:BLUE;\"";
                    }
                    if ($head->STATUS == 30) {
                        echo "style=\"color:GREEN;\"";
                    }
                    ?>>
                        <td><a target="_blank" title='Select Enquiry' href="<?php echo $this->url(array('controller' => 'enquiries', 'action' => 'update', 'enq_no' => $head->ENQ_NO),null,true); ?>" class="ui-button ui-button-icon-left ui-state-default ui-corner-all"><span class="ui-icon ui-icon-circle-triangle-e"></span></a> </td>
                        <td>&nbsp;</td>
                        <td><a target="_blank" title='Copy Enquiry' href="<?php echo $this->url(array('controller' => 'enquiries', 'action' => 'update', 'f' => 'C', 'enq_no' => $head->ENQ_NO),null,true); ?>" class="ui-button ui-button-icon-left ui-state-default ui-corner-all"><span class="ui-icon ui-icon-copy"></span></a> </td>
                        <td>&nbsp;</td>
                        <td style="text-align:left;"> <?= $head->ENQ_NO; ?> </td>
                        <td>&nbsp;</td>
                        <td style="text-align:left;"> <?= $head->ENQUIRER; ?> </td>
                        <td>&nbsp;</td>
                        <td style="text-align:left;"> <?= $head->COMPANY; ?> </td>
                        <td>&nbsp;</td>

                        <?php
                        if (trim($head->EMAIL) <> '') {
                            echo "<td style='text-align:center;'><a id='emailLink' title='Send Email to " . trim($head->ENQUIRER) . "' href='mailto:" . $head->EMAIL . "' class='ui-button ui-button-icon-left ui-state-default ui-corner-all'><span class='ui-icon ui-icon-mail-closed'></span></a> </td>";
                        } else {
                            echo "<td>&nbsp</td>";
                        }
                        ?>

                        <td>&nbsp;</td>
                        <td><?= $head->TELEPHONE; ?></td>
                        <td>&nbsp;</td>
                        <td><?= $head->LOCATION; ?></td>
                        <td>&nbsp;</td>
                        <td><?= $head->PRICE; ?></td>
                        <td>&nbsp;</td>
                        <td><?= getStatusDescription($head->STATUS); ?></td>
                        <td>&nbsp;</td>
                        <td style="text-align:center;"><?= getFullDate($head->CHASED_DATE); ?></td>
                        <td>&nbsp;</td>
                        <td style="text-align:center;"><?= getFullDate($head->FOLLOW_UP); ?></td>
                        <td>&nbsp;</td>
                        <td style="width: 20px"><a title="Spoilt Enquiry" href="<?php echo $this->url(array('controller' => 'enquiries', 'action' => 'spoilt', 'enq_no' => $head->ENQ_NO),null,true); ?>" class="ui-button ui-button-icon-left ui-state-default ui-corner-all"><span class="ui-icon ui-icon-trash"></span></a></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>

<?= $this->tab_switch ?>
